apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: uppsikc@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: clerikc-certificate
spec:
  secretName: clerikc-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: clerikc.ru
  dnsNames:
  - clerikc.ru