apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
  namespace: default
data:
  default.conf: |
    server {
      listen 80;
      server_name clerikc.ru www.clerikc.ru;
      return 301 https://$server_name$request_uri;
    }

    server {
      listen 443 ssl http2;
      server_name clerikc.ru www.clerikc.ru;

      ssl_certificate /etc/ssl/certs/tls.crt;
      ssl_certificate_key /etc/ssl/private/tls.key;
      
      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      # Дополнительные настройки
      client_max_body_size 100M;
      proxy_read_timeout 300;
    }

  custom-server.conf: |
    # Дополнительные серверные блоки можно добавлять здесь
    # Этот файл будет включен в основную конфигурацию